name: "Claude Code Action"            # Nom du workflow
on:                                   
  pull_request:                       # Se déclenche à chaque PR
    types: [opened, synchronize, reopened]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # déclenche automatiquement une review sur la PR
