name: "Claude Code Action"            # Nom du workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:                         # Ajout de la permission OIDC
  id-token: write
  contents: read                     # autorise la lecture du repo

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          # Utilise le secret que la CLI a créé : CLAUDE_CODE_OAUTH_TOKEN
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Le jeton GitHub fourni par GitHub Actions
          github_token:        ${{ secrets.GITHUB_TOKEN }}
