name: Déclenchement déploiement Frontend

# À chaque push sur main
on:
  push:
    branches:
      - main

jobs:
  trigger_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Déclenche Render Static Site Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
